ORDER_QTY = 0.001

WEBHOOK_SECRET = "1234"

DEFAULT_SYMBOL = "BTCUSDT"

# 🔥 실거래 / 테스트넷
TESTNET = False

MAX_TRADES_PER_MIN = 3

TRAILING_STEP = 0.5
MAX_DAILY_LOSS = -3.0

# Telegram
TELEGRAM_TOKEN = "YOUR_TELEGRAM_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID"
