ORDER_QTY = 0.001

WEBHOOK_SECRET = "1234"

DEFAULT_SYMBOL = "BTCUSDT"

TESTNET = False

MAX_TRADES_PER_MIN = 3

MAX_DAILY_LOSS = -3.0

TELEGRAM_TOKEN = "YOUR_TELEGRAM_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID"

USE_AI_FILTER = True

# 다중 코인
SYMBOLS = ["BTCUSDT", "ETHUSDT", "SOLUSDT"]
