version: "3.9"

services:

  bot:
    build: .
    container_name: trading_bot
    restart: always

    env_file:
      - .env

    expose:
      - "5000"

    command: python app.py

    networks:
      - botnet


  watchdog:
    build: .
    container_name: watchdog
    restart: always

    depends_on:
      - bot

    env_file:
      - .env

    command: python watchdog.py

    networks:
      - botnet


  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

    depends_on:
      - bot

    networks:
      - botnet


networks:
  botnet:
