events {}

http {

    server {

        listen 80;
        server_name your-domain.com;

        location / {
            proxy_pass http://bot:5000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
    }

    server {

        listen 443 ssl;
        server_name your-domain.com;

        ssl_certificate /etc/letsencrypt/live/your-domain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/your-domain.com/privkey.pem;

        location / {
            proxy_pass http://bot:5000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
