events {}

http {

    server {

        listen 80;

        location / {

            proxy_pass http://bot:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /webhook {

            proxy_pass http://bot:5000/webhook;
        }

        location /health {

            proxy_pass http://bot:5000/health;
        }
    }
}
